version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=parthproject
      - MONGO_URI=mongodb+srv://parthnandaniya:vz4pIYUedvUZ5Udc@cluster0.jdgo5sh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - '3000:3000'
